# Generated by Django 5.2.5 on 2025-08-18 14:36

import voice_recognition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationuservoice',
            name='sample',
            field=models.FileField(upload_to=voice_recognition.models.register),
        ),
        migrations.AlterField(
            model_name='verificationuservoice',
            name='sample',
            field=models.FileField(upload_to=voice_recognition.models.verify),
        ),
    ]
