# Generated by Django 5.2.5 on 2025-08-15 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticUserVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.FileField(upload_to='voice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sample', 'user'), name='one-sample-one-user-unique')],
            },
        ),
    ]
