# Generated by Django 5.2.5 on 2025-08-15 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authenticuservoice',
            name='one-sample-one-user-unique',
        ),
        migrations.AlterField(
            model_name='authenticuservoice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to=settings.AUTH_USER_MODEL),
        ),
    ]
