# Generated by Django 5.2.5 on 2025-08-18 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_message', models.CharField()),
                ('response_message', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
